### ISSUE TITLE
重要提示！！！

### ISSUE THREAD

**Issue by HuiguoRose** [windosx/go-don#1]
你好，我是通过虹软的人脸识别项目进入到这个仓库里的。 发现了一个比较特殊的网站。 我还从历史的提交里找到了账号密码，我尝试登陆一下，竟然可以成功的登陆进去。之后顺手和客服要了个邀请码，自己注册了一个账号。 希望你可以保护好自己的账号~

**Comment by windosx** [comment]
@HuiguoRose 多谢多谢，不过多了一个道友也挺不错的，哈哈。那个”特殊网站“改了一次版，所以这个项目也废了，准备删掉了。
